import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface HealthReading {
  createdAt: Date;
  bloodPressureSystolic?: number | null;
  bloodPressureDiastolic?: number | null;
  heartRate?: number | null;
  weight?: string | null;
  height?: string | null;
  bmi?: string | null;
  temperature?: string | null;
  notes?: string | null;
}

export interface HealthScoreSnapshot {
  score: number;
  grade: string;
  gradeColor: string;
  components: { label: string; value: number; color: string }[];
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function addHeader(doc: jsPDF, title: string, subtitle: string) {
  // Teal header bar
  doc.setFillColor(8, 145, 178); // cyan-600
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Tech Care", 14, 12);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(title, 14, 20);

  doc.setFontSize(9);
  doc.setTextColor(200, 240, 255);
  doc.text(subtitle, 14, 26);

  doc.setTextColor(40, 40, 40);
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Tech Care · Page ${i} of ${pageCount} · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
      14,
      doc.internal.pageSize.height - 8
    );
  }
}

// ─── Health Scores PDF ────────────────────────────────────────────────────────

export function downloadHealthScoresPDF(
  readings: HealthReading[],
  healthScore: HealthScoreSnapshot | null,
  userName: string
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const now = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  addHeader(doc, "Health Scores Report", `Patient: ${userName} · Generated: ${now}`);

  let y = 36;

  // ── Overall Health Score ──
  if (healthScore) {
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(8, 145, 178);
    doc.text("Overall Health Score", 14, y);
    y += 7;

    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(40, 40, 40);
    doc.text(`${healthScore.score}/100`, 14, y + 6);

    doc.setFontSize(14);
    doc.setTextColor(100, 100, 100);
    doc.text(`Grade: ${healthScore.grade}`, 60, y + 6);
    y += 18;

    // Component breakdown table
    autoTable(doc, {
      startY: y,
      head: [["Component", "Score / 100"]],
      body: healthScore.components.map((c) => [c.label, `${c.value}/100`]),
      theme: "striped",
      headStyles: { fillColor: [8, 145, 178], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 10, cellPadding: 3 },
      margin: { left: 14, right: 14 },
    });

    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  }

  // ── Latest Vitals ──
  const latest = readings[0];
  if (latest) {
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(8, 145, 178);
    doc.text("Latest Vitals", 14, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [["Metric", "Value", "Unit"]],
      body: [
        ["Blood Pressure", latest.bloodPressureSystolic && latest.bloodPressureDiastolic ? `${latest.bloodPressureSystolic}/${latest.bloodPressureDiastolic}` : "—", "mmHg"],
        ["Heart Rate", latest.heartRate?.toString() ?? "—", "bpm"],
        ["Weight", latest.weight ?? "—", "kg"],
        ["Height", latest.height ?? "—", "cm"],
        ["BMI", latest.bmi ?? "—", "kg/m²"],
        ["Temperature", latest.temperature ?? "—", "°C"],
      ],
      theme: "striped",
      headStyles: { fillColor: [8, 145, 178], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 10, cellPadding: 3 },
      margin: { left: 14, right: 14 },
    });

    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  }

  // ── Full Reading History ──
  if (readings.length > 0) {
    // New page if not enough space
    if (y > 220) { doc.addPage(); y = 20; }

    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(8, 145, 178);
    doc.text("Reading History", 14, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [["Date", "BP (mmHg)", "HR (bpm)", "Weight (kg)", "BMI", "Temp (°C)"]],
      body: readings.map((r) => [
        new Date(r.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" }),
        r.bloodPressureSystolic && r.bloodPressureDiastolic ? `${r.bloodPressureSystolic}/${r.bloodPressureDiastolic}` : "—",
        r.heartRate?.toString() ?? "—",
        r.weight ?? "—",
        r.bmi ?? "—",
        r.temperature ?? "—",
      ]),
      theme: "striped",
      headStyles: { fillColor: [8, 145, 178], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, cellPadding: 2.5 },
      margin: { left: 14, right: 14 },
    });
  }

  addFooter(doc);
  doc.save(`TechCare_HealthReport_${userName.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ─── AI Plan PDF ──────────────────────────────────────────────────────────────

/**
 * Parse the AI plan markdown content and extract a weekly schedule table if present.
 * Returns { sections: string[], weeklyTable: { headers: string[], rows: string[][] } | null }
 */
function parseAIPlanContent(content: string): {
  textSections: string[];
  weeklyTable: { headers: string[]; rows: string[][] } | null;
} {
  const lines = content.split("\n");
  const textSections: string[] = [];
  const weeklyTable: { headers: string[]; rows: string[][] } | null = null;
  let tableHeaders: string[] = [];
  const tableRows: string[][] = [];
  let inTable = false;
  let headerParsed = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Detect markdown table rows
    if (trimmed.startsWith("|") && trimmed.endsWith("|")) {
      inTable = true;
      const cells = trimmed
        .split("|")
        .slice(1, -1)
        .map((c) => c.trim());

      // Skip separator rows like |---|---|
      if (cells.every((c) => /^[-:]+$/.test(c))) {
        headerParsed = true;
        continue;
      }

      if (!headerParsed) {
        tableHeaders = cells;
      } else {
        tableRows.push(cells);
      }
    } else {
      if (inTable) {
        inTable = false;
      }
      if (trimmed) {
        // Strip markdown formatting for plain text
        const plain = trimmed
          .replace(/^#{1,6}\s+/, "")
          .replace(/\*\*(.*?)\*\*/g, "$1")
          .replace(/\*(.*?)\*/g, "$1")
          .replace(/`(.*?)`/g, "$1");
        textSections.push(plain);
      }
    }
  }

  return {
    textSections,
    weeklyTable: tableHeaders.length > 0 && tableRows.length > 0
      ? { headers: tableHeaders, rows: tableRows }
      : null,
  };
}

export function downloadAIPlanPDF(
  planContent: string,
  planType: string,
  userName: string,
  createdAt: Date
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const dateStr = new Date(createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const planLabel = planType === "health" ? "Health Plan" : planType === "diet" ? "Diet Plan" : "Full Wellness Plan";

  addHeader(doc, `${planLabel}`, `Patient: ${userName} · Created: ${dateStr}`);

  let y = 36;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;
  const maxWidth = pageWidth - margin * 2;

  const { textSections, weeklyTable } = parseAIPlanContent(planContent);

  // Render text sections
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);

  for (const section of textSections) {
    // Detect headings (originally started with #)
    const isHeading = /^(Overview|Summary|Goals|Week|Day|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|Morning|Afternoon|Evening|Breakfast|Lunch|Dinner|Snack|Exercise|Diet|Health|Lifestyle|Sleep|Stress|Hydration|Nutrition|Meal|Plan|Schedule|Recommendations|Tips|Notes)/i.test(section);

    if (isHeading) {
      if (y > 260) { doc.addPage(); y = 20; }
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(8, 145, 178);
      doc.text(section, margin, y);
      y += 7;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(50, 50, 50);
    } else {
      const lines = doc.splitTextToSize(section, maxWidth);
      if (y + lines.length * 5 > 270) { doc.addPage(); y = 20; }
      doc.text(lines, margin, y);
      y += lines.length * 5 + 2;
    }
  }

  // Render weekly table if found
  if (weeklyTable) {
    if (y > 220) { doc.addPage(); y = 20; }
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(8, 145, 178);
    doc.text("Weekly Schedule", margin, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [weeklyTable.headers],
      body: weeklyTable.rows,
      theme: "grid",
      headStyles: { fillColor: [8, 145, 178], textColor: 255, fontStyle: "bold", fontSize: 9 },
      styles: { fontSize: 8.5, cellPadding: 2.5, overflow: "linebreak" },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 28 } },
      margin: { left: margin, right: margin },
    });
  }

  addFooter(doc);
  doc.save(`TechCare_${planLabel.replace(/\s+/g, "_")}_${userName.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`);
}
